apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: ${SERVICE_API_IMAGE_NAME}
          ports:
            - containerPort: 3100
          env:
            - name: AZURE_CLIENT_ID
              value: ${AZURE_AKS_IDENTITY_CLIENT_ID}
            - name: AZURE_KEY_VAULT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: azd
                  key: AZURE_KEY_VAULT_ENDPOINT
                  optional: false
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azd
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
                  optional: false
